version: '3'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ".:/usr/local/go/src/Inservice"
    ports:
      - "8080:8080"
    restart: always
    # tty: true
