version: '3'
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ".:/go/src/app"
    ports:
      - "8080:8080"
      # - "5000:5000"
    restart: always